services:
  app:
    build: .
    container_name: notify-hub-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: notify-hub-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: